---
title: "Sobre esse site"
description: |
  Entendendo alguns "porquês" ...
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Objetivo desse site

Esse site tem por objetivo organizar a teoria, *slides* e vídeos do minicurso 
ofertado de forma **remota** no semestre acadêmico de 2021.1/2021.2 da [UFRB][UFRB], 
no [Centro de Formação de Professores][CFP], em Amargosa-BA.

[UFRB]: https://ufrb.edu.br/portal/
[CFP]: https://www.ufrb.edu.br/cfp/

# Objetivos a longo prazo

Uma das intenções de oferecer esse minicurso é gerar material, bem como 
analisar uma estruturação de um futuro **Programa de Extensão** que envolverá, 
dentre outras coisa, ofertas de cursos para o professor de matemática (ou
a quem interessar) que ajudem na "formação tecnológica", essencial para lidar
com dados e produtividade de sua área de atuação.

Os cursos serão (a lista não está finalizada):

  - [$\LaTeX$][LATEX]; uma linguagem de marcação para produção de documentos
    tipograficamente adequados à área de matemática e afins. 
  - [Git][GIT] e [GitHub][GITHUB]; para versionamento de arquivos.
  - [**R**][R], na perspectiva do [*tidyverse*][TIDY]; liguagem e ambiente de 
    programação com ferramentas estatísticas diversas para analise de dados; 
    produção textual; construção de sites; etc.
  - [SageMath][SAGE]; uma alternativa livre para o *software* Maple.
  - ...

[LATEX]: https://www.latex-project.org/
[GIT]: https://git-scm.com/
[GITHUB]: https://github.com/
[R]: https://www.r-project.org/
[TIDY]: https://www.tidyverse.org/
[SAGE]: https://www.sagemath.org/

Obviamente, a preferencia será por *softwares livres*.

# Como foi feito esse site e o material do minicurso?

Todo material, bem como esse próprio *site*, foram construídos com a linguagem 
**R**.
Na realidade, usamos certos pacotes que utilizam o **R**  como base.

Especificamente:

  - Usamos o [`distill`][DIS] para construir o *site*
    + o pacote [`xaringanExtra`][EXTRA] foi usado para criar os "paineis", 
    ativando a função `use_panelset()`;
  - Usamos o [`Xaringan`][XAR] para os *slides*;
  - Usamos o [`learnr`][TUTO] para os tutoriais.
  
[DIS]: https://rstudio.github.io/distill/
[EXTRA]: https://pkg.garrickadenbuie.com/xaringanExtra/#/
[XAR]: https://slides.yihui.org/xaringan/#1
[TUTO]: https://rstudio.github.io/learnr/index.html

# Onde encontro os códigos?

Todos os códigos estão diponíveis no GitHub [^cat].
Para acessar, basta clicar no ícone de um "gatinho preto" na *Home* desse *site*,
ou visite o *link*:

<p align='center'>
  https://github.com/icaro-freire/minicurso_web-scraping
</p>

[^cat]: "plataforma de hospedagem de código-fonte e arquivos com controle de
versão usando o **Git**" (Wikpédia)